import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  }
};

export default function RootLayout({ children, params, modal }) {
  const lang = params.lang;
  return (
    <html lang="en">
      <body>
        <Navbar lang={lang} />

        {modal}
        {children}
        <Footer lang={lang} />
      </body>
    </html>
  );
}
